version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: demo_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shop123
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports:
      - "30306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0
    container_name: demo_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  crm.shopdev.com:
    container_name: go_backend_crm_shopdev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8008:8082"

volumes:
  mysql_data:
  redis_data: