// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/haodam/user-backend-golang/internal/modules/user/handler"
	"github.com/haodam/user-backend-golang/internal/modules/user/repository"
	"github.com/haodam/user-backend-golang/internal/modules/user/usecase"
)

// Injectors from user_wire.go:

func InitUserRouterHandler() (*handler.UserHandler, error) {
	iUserRepository := repository.NewUserRepository()
	iUserService := usecase.NewUserService(iUserRepository)
	userHandler := handler.NewUserHandler(iUserService)
	return userHandler, nil
}
