// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/haodam/user-backend-golang/internal/modules/user/handler"
	"github.com/haodam/user-backend-golang/internal/modules/user/repository"
	"github.com/haodam/user-backend-golang/internal/modules/user/usecase"
)

// Injectors from user_wire.go: huydeptraivaiz

func InitUserRouterHandler() (*handler.UserHandler, error) {
	iUserRegisterRepository := repository.NewUserRepository()
	iOtpRegisterRepository := repository.NewOtpRegisterRepository()
	iUserRegisterService := usecase.NewUserService(iUserRegisterRepository, iOtpRegisterRepository)
	userHandler := handler.NewUserHandler(iUserRegisterService)
	return userHandler, nil
}
